[frontend]
172.31.39.18 ;COURSE="Ansible for Node-1" #individual host variables

[catalogue]
172.31.25.201

[cart]
172.31.25.202

[user]
172.31.25.223

; group of groups
[roboshop:children]
frontend
catalogue
cart
user

[local]
localhost

; local group vars
[local:vars]
COURSE="DevOps with AIOps"
TRAINER="Kishore"
DURATION="15HRS"
