- name: common role msg-1
  debug:
    msg: "Hi, I'm from common role msg-1"

- name: common role msg-2
  debug:
    msg: "Hi, I'm from common role msg-2"

- name: common role msg-3
  debug:
    msg: "Hi, I'm from common role msg-3"

- name: change the facts
  set_fact:
    os: "Debian"

- name: common role msg-4
  debug:
    msg: "Hi, I'm from common role msg-4"
  
# - name: call role-2
#   include_role:
#     name: role-2